spring.application.name=auth-service

spring.datasource.url=jdbc:postgresql://localhost:5001/auth-service-db
spring.datasource.username=admin
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8081

jwt.secret=yCXCOig72E6SI3yQzMYWT01W9XBw6QWJ0SkihHUq2CZ
