spring.application.name=job-service

spring.datasource.url=jdbc:postgresql://localhost:5000/job-service-db
spring.datasource.username=admin
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect