spring.application.name=application-service

spring.datasource.url=jdbc:postgresql://localhost:5002/application-service-db
spring.datasource.username=admin
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8082