### Get current user profile
GET http://localhost:8081/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsInJvbGUiOiJDQU5ESURBVEUiLCJpZCI6IjhiZjVmYzg0LWYxOTctNDU1OS1hMGQxLTlmNTZkNGVmYjI3OSIsImlhdCI6MTc4MzIwMzkyNCwiZXhwIjoxNzgzMjM5OTI0fQ.K37CfMk2cKgs__QziG2VMPwEL9GvNL31Hc3-lIgK29Y

### Get current user profile with wrong token
GET http://localhost:8081/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXRjaGluZy50ZXN0QGdtYWlsLmNvbSIsInJvbGUiOiJDQU5ESURBVEUiLCJpZCI6IjViOTRjYmJiLTBkOTctNGY1OC05OWVjLWFkNTlkMGI5YzM2NCIsImlhdCI6MTc4MzUzNjgxMywiZXhwIjoxNzgzNTcyODEzfQ.-GuT8HE1OWInMAN3mqpI43S-r1pHjaNvCKgVW94a344