apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: matching-service
  template:
    metadata:
      labels:
        app: matching-service
    spec:
      containers:
        - name: matching-service
          image: matching-service:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8084
          env:
            - name: GRPC_CLIENT_JOB_SERVICE_ADDRESS
              value: static://job-service:9091
            - name: GRPC_CLIENT_AUTH_SERVICE_ADDRESS
              value: static://auth-service:9093