spring.application.name=matching-service

server.port=8084

grpc.client.job-service.address=static://localhost:9091
grpc.client.job-service.negotiation-type=plaintext

grpc.client.auth-service.address=static://localhost:9093
grpc.client.auth-service.negotiation-type=plaintext

grpc.server.port=-1
